config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  get 'about' => 'pages#about'
  # get 'post/:id' => 'posts#show'
  resource :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  self.table_name='user_data'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
    @title = 'About Us'
    @content = 'This is the about page!'
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user_data = User.all.take(50).reverse
  end

  def show
    @userId = User.find(params[:format])
  end

  def new

  end

  def edit
    @userId = User.find(params[:format])
  end

  def update
    @userId = User.find(params[:format])
    if (@userId.update_attributes(post_params))
      redirect_to '/', :notice => 'User was updated'
    else
      render 'edit'
    end
  end

  def create
    @user = User.new(post_params)
    if (@user.save)
      redirect_to '/'
    else
      render 'new'
    end
  end

  def destroy
    User.find(params[:format]).destroy
    flash[:success] = 'User deleted'
    redirect_to '/'
  end

  def post_params
    params.permit(:address, :city, :pupcode, :puptype, :pickuptime, :municipality, :labelname)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'materialize.min', media: 'all', 'data-turbolinks-track': 'reload' %>

</head>

<body>

<nav>
  <div class="nav-wrapper deep-orange">
    <a href="/" class="brand-logo">Stores</a>
    <ul class="right hide-on-med-and-down">
      <li><a href="/">Home</a></li>
      <li><a href="/posts/new">Add User</a></li>
      <!-- Dropdown Trigger -->
      <li>
        <a class="dropdown-button" href="#!" data-activates="dropdown1">Dropdown<i class="material-icons right"></i></a>
      </li>
    </ul>
  </div>
</nav>

<%= yield %>
<%= javascript_include_tag 'https://code.jquery.com/jquery-3.2.1.min.js', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'materialize.min', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'main', 'data-turbolinks-track': 'reload' %>
</body>
</html>

app/views/pages/about.html.erb
<h1><%= @title %></h1>
<p><%= @content %></p>

app/views/posts/edit.html.erb
<div class="container">
  <%= form_for @userId, url: posts_path(@userId), method: :patch do |f| %>
  <h3 class="center">Update</h3>

  <div class="row">
    <div class="input-field col s6">
      <input id="address" name="address" type="text" class="validate" value="<%= @userId.address %>">
      <label for="address">Address</label>
    </div>

    <div class="input-field col s6">
      <input id="city" name="city" type="text" class="validate" value="<%= @userId.city %>">
      <label for="city">City</label>
    </div>
  </div>
  <div class="row">
    <div class="input-field col s3">
      <input id="pup-code" name="pupcode" type="text" class="validate" value="<%= @userId.pupcode %>">
      <label for="pup-code">Pup code</label>
    </div>
    <div class="input-field col s3">
      <input id="pup-type" name="puptype" type="text" class="validate" value="<%= @userId.puptype %>">
      <label for="pup-type">Pup type</label>
    </div>
    <div class="input-field col s3">
      <input id="pickup-time" name="pickuptime" type="text" class="validate" value="<%= @userId.pickuptime %>">
      <label for="pickup-time">Pickup time</label>
    </div>
    <div class="input-field col s3">
      <input id="municipality" name="municipality" type="text" class="validate" value="<%= @userId.municipality %>">
      <label for="municipality">Municipality</label>
    </div>
  </div>
  <div class="row">
    <div class="input-field col s6 offset-s3">
      <input id="label-name" name="labelname" type="text" class="validate" value="<%= @userId.labelname %>">
      <label for="label-name">Label name</label>
    </div>
  </div>
  <div class="center">
    <button class="btn waves-effect waves-light" type="submit" name="action">Update</button>
  </div>


  <% end %>
</div>

app/views/posts/index.html.erb
<h1 class="center">Index</h1>
<div class="container">


  <!-- Modal Trigger -->
  <!--<button data-target="modal1" class="btn modal-trigger">Modal</button>-->

  <!-- Modal Structure -->
  <div id="modal1" class="modal modal-fixed-footer">
    <div class="modal-content">

    </div>
  </div>

  <table>
    <thead>
    <tr>
      <th>Address</th>
      <th>City</th>
      <th>Pup code</th>
      <th>Pup type</th>
      <th>Pickup time</th>
      <th>Municipality</th>
      <th>Label name</th>
      <th>Google Maps</th>
      <th>Update</th>
      <th>Delete</th>
    </tr>
    </thead>
    <tbody>
    <% @user_data.each do |user| %>
            <tr>
              <td>
                <%= user.address %>
              </td>
              <td>
                <%= user.city %>
              </td>
              <td>
                <%= user.pupcode %>
              </td>
              <td>
                <%= user.puptype %>
              </td>
              <td>
                <%= user.pickuptime %>
              </td>
              <td>
                <%= user.municipality %>
              </td>
              <td>
                <%= user.labelname %>
              </td>
              <td>
                <button data-target="modal1" class="btn modal-trigger google-maps" data="<%= user.maplatitude %>,<%= user.maplongitude %>">Map</button>
              </td>
              <td>
                <a href="/posts.<%= user.id %>" id="update-btn" class="btn blue">Show</a>
              </td>
              <td>
                <%= link_to 'delete', posts_path, method: :delete, data: {confirm: 'Are you sure?'}, :class => 'btn red' %>

              </td>
            </tr>

    <% end %>

    </tbody>
  </table>
</div>

app/views/posts/new.html.erb
<div class="container">
  <%= form_for :user, url: posts_path do |f| %>
          <h3 class="center">Update</h3>

          <div class="row">
            <div class="input-field col s6">
              <input id="address" name="address" type="text" class="validate">
              <label for="address">Address</label>
            </div>

            <div class="input-field col s6">
              <input id="city" name="city" type="text" class="validate">
              <label for="city">City</label>
            </div>
          </div>
          <div class="row">
            <div class="input-field col s3">
              <input id="pup-code" name="pupcode" type="text" class="validate">
              <label for="pup-code">Pup code</label>
            </div>
            <div class="input-field col s3">
              <input id="pup-type" name="puptype" type="text" class="validate">
              <label for="pup-type">Pup type</label>
            </div>
            <div class="input-field col s3">
              <input id="pickup-time" name="pickuptime" type="text" class="validate">
              <label for="pickup-time">Pickup time</label>
            </div>
            <div class="input-field col s3">
              <input id="municipality" name="municipality" type="text" class="validate">
              <label for="municipality">Municipality</label>
            </div>
          </div>
          <div class="row">
            <div class="input-field col s6 offset-s3">
              <input id="label-name" name="labelname" type="text" class="validate">
              <label for="label-name">Label name</label>
            </div>
          </div>
          <div class="center">
            <button class="btn waves-effect waves-light" type="submit" name="action">Update</button>
          </div>


  <% end %>
</div>

app/views/posts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col s6 offset-s3">
      <div class="card deep-orange darken-1">
        <div class="card-content white-text">
          <span class="card-title"><%= @userId.city %></span>
          <p>Information about store:</p>
          <p>Address: <%= @userId.address %></p>
          <p>Pup code: <%= @userId.pupcode %></p>
          <p>Pup type: <%= @userId.puptype %></p>
          <p>Pickup time: <%= @userId.pickuptime %></p>
          <p>Municipality: <%= @userId.municipality %></p>
          <p>Label name: <%= @userId.labelname %></p>
        </div>
        <div class="card-action">
          <%= link_to 'Edit', edit_posts_path(@userId) %>
        </div>
      </div>
    </div>
  </div>
</div>